// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7FW9cUb_RoChYSwVQaF6imFx4s-4T8vI',
    appId: '1:519374438161:web:d2816e58b38e084a9e56b0',
    messagingSenderId: '519374438161',
    projectId: 'car-store-615be',
    authDomain: 'car-store-615be.firebaseapp.com',
    storageBucket: 'car-store-615be.appspot.com',
    measurementId: 'G-98VP54JE82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWx-6I28rL0q7eT93Dyze6rQNSOslcXMI',
    appId: '1:519374438161:android:c1ff17f8c10922b79e56b0',
    messagingSenderId: '519374438161',
    projectId: 'car-store-615be',
    storageBucket: 'car-store-615be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBwaHe5eX3o43eU5DUcrxDP4ggzfbh-2E',
    appId: '1:519374438161:ios:f4388c62f519c0e99e56b0',
    messagingSenderId: '519374438161',
    projectId: 'car-store-615be',
    storageBucket: 'car-store-615be.appspot.com',
    iosBundleId: 'com.example.carstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBwaHe5eX3o43eU5DUcrxDP4ggzfbh-2E',
    appId: '1:519374438161:ios:3cd3c1ef415cb0fc9e56b0',
    messagingSenderId: '519374438161',
    projectId: 'car-store-615be',
    storageBucket: 'car-store-615be.appspot.com',
    iosBundleId: 'com.example.carstore.RunnerTests',
  );
}
